services:
  keycloakdb:
    image: postgres:${POSTGRES_VERSION:-16} # Use a default version if not set
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    env_file: .env

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-24.0.4} # Use a default version
    command: start-dev --import-realm
    networks:
      - keycloak-net
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    env_file: .env
    depends_on:
      - keycloakdb

networks:
  keycloak-net:
    driver: bridge

volumes:
  # Define a "named volume" for the database to persist data
  keycloak-db-data:
    name: keycloak-db-data
