version: "3.7"

services:
  keycloakdb:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    command: start-dev --import-realm --import-realm-strategy=OVERWRITE_EXISTING
    networks:
      - internal
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    environment:
      # Keycloak admin user
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      
      # Keycloak database connection settings
      # THE FIX IS HERE: These now correctly use the POSTGRES variables
      KC_DB: postgres
      KC_DB_URL_HOST: keycloakdb
      KC_DB_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
    depends_on:
      - keycloakdb

networks:
  internal:
    driver: bridge

volumes:
  keycloak-postgres:
    name: keycloak-data
