version: '3.3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8024:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_DB=${KEYCLOAK_DATABASE_VENDOR}
      - KC_DB_URL_HOST=${KEYCLOAK_DATABASE_HOST}
      - KC_DB_USERNAME=${KEYCLOAK_DATABASE_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
    command:
      - start-dev
      - --import-realm
      - --import-realm-strategy=OVERWRITE_EXISTING
    volumes:
      - ./keycloak/realms/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ./keycloak/scripts/disable-theme-cache.cli:/opt/keycloak/startup-scripts/disable-theme-cache.cli:ro
      - ./keycloak/themes/custom:/opt/keycloak/themes/custom:ro
    networks:
      - internal
    depends_on:
      - keycloakdb

  keycloakdb:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${KEYCLOAK_DATABASE_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DATABASE_NAME}
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  keycloak-postgres:

networks:
  internal:
