version: "3.7"

services:
  keycloakdb:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    # This is the line to change. We add the import strategy directly to the command.
    command: start-dev --import-realm --import-realm-strategy=OVERWRITE_EXISTING
    networks:
      - internal
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: ${KEYCLOAK_DATABASE_VENDOR}
      KC_DB_URL_HOST: ${KEYCLOAK_DATABASE_HOST}
      KC_DB_DATABASE: ${KEYCLOAK_DATABASE_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DATABASE_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KC_HOSTNAME: localhost
    depends_on:
      - keycloakdb

networks:
  internal:
    driver: bridge

volumes:
  keycloak-postgres:
    name: keycloak-data
